### ISSUE TITLE
Small fixes Trianon

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim-trianon#4]
- [ ] No "home" button, nowhere : makes navigating not that easy

- [ ]  As a user, when I try to download a profile pic that is too large, instead of an error message the platform ask me too confirm my password
<img width="1546" alt="capture d ecran 2018-02-05 a 17 07 54" src="https://user-images.githubusercontent.com/29771726/35855316-1acee4c8-0b33-11e8-8c3d-b667a5e2abd0.png">

- [ ] As an admin, I get a 413 error when I try to load an oversize image when configuring a feature
<img width="1552" alt="capture d ecran 2018-02-05 a 16 41 12" src="https://user-images.githubusercontent.com/29771726/35855335-29ee3ef4-0b33-11e8-837c-91fe92a385e8.png">

- [ ] Header n'est pas du tout responsive
Tablette
<img width="1193" alt="capture d ecran 2018-02-06 a 11 48 32" src="https://user-images.githubusercontent.com/29771726/35855491-b120b3f2-0b33-11e8-80ab-13e78775e5ec.png">
Mobile
<img width="832" alt="capture d ecran 2018-02-06 a 11 48 13" src="https://user-images.githubusercontent.com/29771726/35855480-a07883d6-0b33-11e8-9cd0-c16bd6fe182e.png">

- [ ] "Show statistics" dans création d'un nouveau process, "delete reason" dans la suppression d'un compte utilisateur en anglais 
<img width="866" alt="capture d ecran 2018-02-05 a 17 08 10" src="https://user-images.githubusercontent.com/29771726/35855301-13d44fc8-0b33-11e8-96e0-b1a926d6fe93.png">
<img width="1552" alt="capture d ecran 2018-02-05 a 16 40 44" src="https://user-images.githubusercontent.com/29771726/35855378-547b5dc8-0b33-11e8-8c46-87adc1b4f6f8.png">

- [ ] Filtre "Elu-e-s" en écriture inclusive mais pas "Citoyens" 
<img width="1552" alt="capture d ecran 2018-02-06 a 11 53 57" src="https://user-images.githubusercontent.com/29771726/35855834-919543a8-0b34-11e8-969c-7ef71497c040.png">

**Comment by virgile-dev** [comment]
Merci @juliesimon pour la liste ! Mes réponses ci-dessous
- [x] No "home" button, nowhere : makes navigating not that easy
_The new header is not ideal, but here Decidim is just one part of the platform. So the Trianon Logo leads back to the root of the website (a joomla powered website)
But I agree we need a way to go back to the participatory process list or home from the nav bar._
<img width="891" alt="capture d ecran 2018-02-06 a 16 39 44" src="https://user-images.githubusercontent.com/11473995/35868310-6e024454-0b5c-11e8-9ce1-961b170322a6.png">
_The "Participez au forum" entry, in the navbar **which we need to add** will be where we put that link._

- [ ]  As a user, when I try to download a profile pic that is too large, instead of an error message the _platform ask me too confirm my password
That's a weird one._

- [ ] As an admin, I get a 413 error when I try to load an oversize image when configuring a feature
_Yup, seen this one I think limit is 1mb._

- [ ] Header n'est pas du tout responsive
_It's actually not too bad. When in mobile everything is in the hamburger menu. We should replicate the behaviour in original site (Joomla) which centers item when in Ipad size_
<img width="530" alt="capture d ecran 2018-02-06 a 16 52 40" src="https://user-images.githubusercontent.com/11473995/35868916-2d42de5e-0b5e-11e8-84c4-acc204712b38.png">

_Although Julie found a screensize where the hamburger menu disappears which is not ideal for navigation : 647px width_
<img width="647" alt="capture d ecran 2018-02-06 a 16 54 47" src="https://user-images.githubusercontent.com/11473995/35869040-7ae43e5a-0b5e-11e8-81d8-c7ec642d38be.png">

We should also harmonize the padding between menu entries in the dropdown menu :
Decidim 
<img width="385" alt="capture d ecran 2018-02-06 a 17 00 14" src="https://user-images.githubusercontent.com/11473995/35869437-4f28b01a-0b5f-11e8-9671-ad7c202e97b5.png">
VS Joomla
<img width="398" alt="capture d ecran 2018-02-06 a 17 00 20" src="https://user-images.githubusercontent.com/11473995/35869442-521a13ae-0b5f-11e8-9af5-f53a1179dbf9.png">

- [ ] "Show statistics" dans création d'un nouveau process, "delete reason" dans la suppression d'un compte utilisateur en anglais 
With translation overrides file we should be fine I think.

- [ ] Filtre "Elu-e-s" en écriture inclusive mais pas "Citoyens" 
With translation overrides file this is how we translated it : 
"Elu-e-s" --> Propositions officielles
"Citoyens" --> Proposition citoyennes
